FROM ubuntu
RUN apt-get update && apt-get upgrade -y
RUN apt-get install nginx -y
RUN apt-get install nodejs -y
RUN apt-get install npm -y 
COPY ./mxr-web/apps/nocode ./nocode
WORKDIR /nocode
RUN npm -v
RUN npm install
RUN npm run build
RUN cp -r ./build/* /var/www/html
CMD ["nginx","-g","daemon off;"]